services:
  backend:
    image: crunchypandesal/docusphere-api:dev
    command: php artisan test
    ports:
      - "8000:8000"
    environment:
      APP_ENV: testing
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: docusphere
      DB_USERNAME: postgres
      DB_PASSWORD: binbin
      APP_KEY: ${APP_KEY}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      CLOUDINARY_KEY: ${CLOUDINARY_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: binbin
      POSTGRES_DB: docusphere
    volumes:
      - postgres_data:/var/lib/postgresql

  frontend:
    image: crunchypandesal/docusphere-fe:dev
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_FRONTEND_URL: http://localhost:3000
      VITE_SUPER_ADMIN: docusphere@admin.com

volumes:
  postgres_data:

