services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: docusphere
      DB_USERNAME: postgres
      DB_PASSWORD: binbin

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: binbin
      POSTGRES_DB: docusphere
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

