FROM php:8.2-fpm-alpine

WORKDIR /app


# Install system dependencies and PHP extensions
RUN apk add --no-cache \
    zip \
    libzip-dev \
    libxml2-dev \
    postgresql-dev \
    postgresql-client \
    curl-dev \
    libcurl \
    oniguruma-dev \
    && rm -rf /var/cache/apk/*

# Install PHP extensions
RUN docker-php-ext-install mbstring curl zip pdo_pgsql pgsql xml fileinfo

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

# Install PHP dependencies using Composer
RUN composer install --optimize-autoloader --no-scripts --no-interaction

# Copy application files to the container
COPY . .

RUN php artisan package:discover --ansi


# Configure PHP settings for file uploads
RUN echo "upload_max_filesize=10M" > /usr/local/etc/php/conf.d/upload.ini && \
    echo "post_max_size=10M" >> /usr/local/etc/php/conf.d/upload.ini && \
    echo "memory_limit=128M" >> /usr/local/etc/php/conf.d/upload.ini && \
    echo "max_execution_time=300" >> /usr/local/etc/php/conf.d/upload.ini


# Expose the application port
EXPOSE 8000

# Start the Laravel development server
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

